### ISSUE TITLE
StagingFailed error for pushing .net application windows stack 

### ISSUE THREAD

**Issue by cfmagnum** [cloudfoundry/garden-windows-release#5]
CloudFoundary version-250
diego/1.4.1
windows windows2012R2
Cloud- aws 
windows cell size-r3.xlarge

Hi i am trying to push a .net application on windows stack.But after starting the applicationn its giving staging failed error.
I am pushing app from repo  https://github.com/cloudfoundry/wats

Using Buildpack is  https://github.com/ryandotsmith/null-buildpack

Command for pushing app are as followed.

**cf push windows-test-app-1 -s windows2012R2 -b https://github.com/ryandotsmith/null-buildpack.git -m 1G --no-start**
**cf start windows-test-app-1**
I am attaching output of  CF_TRACE 
[cf_trace=true.txt](https://github.com/cloudfoundry/diego-release/files/823559/cf_trace.true.txt)
.

on checking logs with command 
**cf logs windows-test-app-1 --recent**
![screen shot 03-07-17 at 12 09 pm](https://cloud.githubusercontent.com/assets/13657881/23644759/ed2694f6-032e-11e7-9116-163858a9b35b.PNG)

Can you please assist us with the problem?
Thanks in Advance

**Comment by sunjayBhatia** [comment]
Closing, discussion can be container here: https://github.com/cloudfoundry/diego-windows-release/issues/24
